server:
  port: 8081
  error:
    path: /error

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/supportportal"
    username: supportportal
    password: supportportal
    initialization-mode: embedded
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    add-properties: true

jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

app:
  corsallowedorigins:
    - http://localhost:3000
    - http://localhost:4200

logging:
  level:
    web: debug

info:
  app:
    name: User Manager Application
    description: This is an application to manage users
    version: 1.0
