export enum Role {
  USER = 'ROLE_USER',
  MANAGER_AUTHORITIES = 'ROLE_MANAGER_AUTHORITIES',
  ADMIN_AUTHORITIES = 'ROLE_ADMIN_AUTHORITIES',
  SUPER_ADMIN_AUTHORITIES = 'ROLE_SUPER_ADMIN_AUTHORITIES',
}
